# Default values for mcp-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Required: Alibaba Cloud Access Key ID
accessKeyId: <your-access-key-id>
# Required: Alibaba Cloud Access Key Secret
accessKeySecret: <your-access-key-secret>

transport: sse
port: 8000
allowWrite: true

image:
  registry: registry-cn-beijing.ack.aliyuncs.com/acs/ack-mcp-server
  tag: "v1.0.0-73a8c94-aliyun"
  pullPolicy: Always

# Probes (disabled as per requirements)
livenessProbe: { }
readinessProbe: { }

serviceAccount:
  create: true
  annotations: { }

# Replica count for each service
replicaCount: 1
