apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-demo-app
  labels:
    app: cost-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cost-demo-app
  template:
    metadata:
      labels:
        app: cost-demo-app
    spec:
      containers:
        - name: app-container
          image: registry-cn-beijing.ack.aliyuncs.com/acs/docker-stress:v1.0.1-f69a43e-aliyun
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          args:
            - --vm
            - "1"
            - --vm-bytes
            - 40M
            - --timeout
            - 3600s
